### ISSUE TITLE
webhook error

### ISSUE THREAD

**Issue by upgradepa** [yagop/node-telegram-bot-api#1016]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

node:internal/tls/secure-context:69
    context.setCert(cert);
            ^

Error: error:0909006C:PEM routines:get_name:no start line
    at node:internal/tls/secure-context:69:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:67:3)
    at configSecureContext (node:internal/tls/secure-context:156:5)
    at Object.createSecureContext (node:_tls_common:121:3)
    at Server.setSecureContext (node:_tls_wrap:1349:27)
    at Server (node:_tls_wrap:1208:8)
    at new Server (node:https:73:3)
    at Object.createServer (node:https:109:10)
    at new TelegramBotWebHook (/root/transnodebot/node_modules/node-telegram-bot-api/src/telegramWebHook.js:31:31)
    at TelegramBot.openWebHook (/root/transnodebot/node_modules/node-telegram-bot-api/src/telegram.js:577:23)
    at new TelegramBot (/root/transnodebot/node_modules/node-telegram-bot-api/src/telegram.js:184:14)
    at Object.telegrambot (/root/transnodebot/telegram/bot.js:25:17)
    at Object.<anonymous> (/root/transnodebot/index.js:4:4)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)                                                                           
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)                                                                 
    at node:internal/main/run_main_module:17:47 {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}

### Actual Behavior
when i create bot with webhook

### Steps to reproduce the Behavior

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Example

> Question

**Comment by yagop** [comment]
`ERR_OSSL_PEM_NO_START_LINE` ("no start line") comes from Node's TLS layer, not from this library: the `key`/`cert` you handed the HTTPS webhook server isn't a valid PEM. The most common causes:

- Passing the certificate **contents** (a string) where a **file path** is expected (in v1.x these options are paths that are read with `readFileSync`).
- An empty / wrong file, or a DER (binary) cert instead of PEM.
- Key and cert swapped, or only one of the two provided.

A valid PEM begins with a line like `-----BEGIN PRIVATE KEY-----` / `-----BEGIN CERTIFICATE-----`. Verify with `openssl x509 -in cert.pem -noout -text` and `openssl rsa -in key.pem -check`.

That said, the recommended setup today is to **not** terminate TLS in Node at all: put nginx (or any reverse proxy) in front, let it handle HTTPS, and run the webhook server over plain HTTP locally:

```js
const bot = new TelegramBot(token, {
  webHook: { host: "127.0.0.1", port: 8443 } // no key/cert; nginx does TLS
});
await bot.setWebHook("https://your.domain/bot" + token);
```

Closing as a certificate/config issue rather than a library bug.
