### ISSUE TITLE
Polling error

### ISSUE THREAD

**Issue by ALVINTAN159** [yagop/node-telegram-bot-api#1045]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Steps to reproduce the Behavior

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Example

> Question

**Comment by illixion** [comment]
I'm also encountering this error, here's the exception message:

```js
Error: xhr poll error
    at Polling.onError (/Users/user/Projects/telegram-bot/node_modules/engine.io-client/build/cjs/transport.js:46:37)
    at Request.<anonymous> (/Users/user/Projects/telegram-bot/node_modules/engine.io-client/build/cjs/transports/polling.js:255:18)
    at Emitter.emit (/Users/user/Projects/telegram-bot/node_modules/@socket.io/component-emitter/index.js:143:20)
    at Request.onError (/Users/user/Projects/telegram-bot/node_modules/engine.io-client/build/cjs/transports/polling.js:356:14)
    at Timeout._onTimeout (/Users/user/Projects/telegram-bot/node_modules/engine.io-client/build/cjs/transports/polling.js:329:30)
    at listOnTimeout (/Users/user/Projects/telegram-bot/lib/internal/timers.js:564:17)
    at process.processTimers (node:internal/timers:507:7) {description: 0, context: XMLHttpRequest, type: 'TransportError', stack: 'Error: xhr poll error
    at Polling.onError …ss.processTimers (node:internal/timers:507:7)', message: 'xhr poll error'}
```

**Comment by danielperez9430** [comment]
Hi @ALVINTAN159 we need more info that only this message. You can get more infomation if you add to your bot code this:


```js
// Listen polling errors events

bot.on('polling_error', (error) => {
  // console.log(error)
  console.log("Polling error code: ",error.code);
  console.log("Error Message: ", error.message);
  console.log("Stack trace: ", error.stack);
});
```
