### ISSUE TITLE
please help me i got this error

### ISSUE THREAD

**Issue by MuftukMall** [yagop/node-telegram-bot-api#1193]
RequestError: AggregateError
    at new RequestError (/opt/render/project/src/node_modules/request-promise-core/lib/errors.js:14:15)
    at plumbing.callback (/opt/render/project/src/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/opt/render/project/src/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/opt/render/project/src/node_modules/@cypress/request/request.js:183:22)
    at Request.emit (node:events:518:28)
    at Request.onRequestError (/opt/render/project/src/node_modules/@cypress/request/request.js:869:8)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EFATAL'
}

**Comment by pratansyah** [comment]
Got the same problem, my own investigation has pinned down that the problem comes from cypress/request library. Will try to investigate further later.

**Comment by ivanjh** [comment]
Newer Node introduced "smarts" and caused the problem for me: https://github.com/nodejs/node/issues/54359
Try running node with `--no-network-family-autoselection`
