### ISSUE TITLE
Handling invalid token

### ISSUE THREAD

**Issue by nodegin** [yagop/node-telegram-bot-api#156]
Hello, I am trying to handle the case for invalid token

Here's my code snippet:

``` js
const callback = async (req, res) => {
  try {
    const bot = new telegramBot(req.body.token+'s', {
      polling: true
    })
    const info = await bot.getMe()
    console.log(info)
  } catch (e) {
    console.log('error')
  }
  res.send(null)
}
```

But instead of seeing `error` on the terminal, the script keeps printing the following result:

```
Unhandled rejection Error: 401 {"ok":false,"error_code":401,"description":"Unauthorized"}
[0]     at /Users/me/Desktop/tgbot/node_modules/node-telegram-bot-api/lib/telegramPolling.js:126:17
[0]     at tryOnImmediate (timers.js:543:15)
[0]     at processImmediate [as _immediateCallback] (timers.js:523:5)
[0] From previous event:
[0]     at TelegramBotPolling._getUpdates (/Users/me/Desktop/tgbot/node_modules/node-telegram-bot-api/lib/telegramPolling.js:120:74)
[0]     at TelegramBotPolling._polling (/Users/me/Desktop/tgbot/node_modules/node-telegram-bot-api/lib/telegramPolling.js:46:31)
[0]     at Timeout._onTimeout (/Users/me/Desktop/tgbot/node_modules/node-telegram-bot-api/lib/telegramPolling.js:63:26)
[0]     at tryOnTimeout (timers.js:224:11)
[0]     at Timer.listOnTimeout (timers.js:198:5)
[0] Unhandled rejection Error: 401 {"ok":false,"error_code":401,"description":"Unauthorized"}
[0]     at /Users/me/Desktop/tgbot/node_modules/node-telegram-bot-api/lib/telegramPolling.js:126:17
[0]     at tryOnImmediate (timers.js:543:15)
[0]     at processImmediate [as _immediateCallback] (timers.js:523:5)
[0] From previous event:
[0]     at TelegramBotPolling._getUpdates (/Users/me/Desktop/tgbot/node_modules/node-telegram-bot-api/lib/telegramPolling.js:120:74)
[0]     at TelegramBotPolling._polling (/Users/me/Desktop/tgbot/node_modules/node-telegram-bot-api/lib/telegramPolling.js:46:31)
[0]     at Timeout._onTimeout (/Users/me/Desktop/tgbot/node_modules/node-telegram-bot-api/lib/telegramPolling.js:63:26)
[0]     at tryOnTimeout (timers.js:224:11)
[0]     at Timer.listOnTimeout (timers.js:198:5)
```

where I should already catching all errors, here's the output after transpilation:

``` js
const callback = (req, res) => {
  return Promise.resolve().then(function () {
    return Promise.resolve().then(function () {
      const bot = new telegramBot(req.body.token + 's', {
        polling: true
      });
      return bot.getMe();
    }).then(function (_resp) {
      const info = _resp;
      console.log(info);
    }).catch(function (e) {
      console.log('error');
    });
  }).then(function () {
    res.send(null);
  });
};
```

Any help is appreciated, thanks

**Comment by Leestex** [comment]
@nodegin the easiest way to handle it is to create a bot instance without passing `polling` option, run `getMe()` first and than if it succeed - start polling:

```js
const Telegram = require('node-telegram-bot-api');

const callback = (req, res) => {
  const bot = new Telegram(req.body.token);
  bot.getMe()
    .then((info) => {
      console.log(info);
      bot.initPolling();
    })
    .catch((e) => {
        console.log('error');
    });
```

**Comment by nodegin** [comment]
@Leestex Good solution, thank you!

**Comment by GochoMugo** [comment]
@Leestex Nice! Seems the `TelegramBot.initPolling()` method is undocumented.

**Comment by hems** [comment]
@Leestex that solution doesn't work for me, the timeouts still happen. does using initPolling change anything?
