### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by samanmohamadi** [yagop/node-telegram-bot-api#166]
Seems to be node v6 error.
Gettign this error when trying to send photo as stream : 
`bot.sendPhoto(id,stream)`

Error:
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at TelegramBot._formatSendData (/srv/http/bot/node_modules/node-telegram-bot-api/lib/telegram.js:350:35)
    at TelegramBot.sendPhoto (/srv/http/bot/node_modules/node-telegram-bot-api/lib/telegram.js:407:26)
    at onWidthFound (/srv/http/bot/watermark.js:37:11)
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:1
```2

**Comment by GochoMugo** [comment]
Please ensure `stream` is actually a Stream and **not** `undefined` as the error explains. It is detected as a stream [at this point in the code](https://github.com/yagop/node-telegram-bot-api/blob/e0e5e9a7b0cbf823e008704b76d614e5da6e2922/src/telegram.js#L296).

**Comment by GochoMugo** [comment]
Your bug might have [been addressed in this PR](https://github.com/yagop/node-telegram-bot-api/pull/204). Please confirm so we can close this issue.

**Comment by samanmohamadi** [comment]
unfortunately I don't work on that project and I can't test it right now, So I close this issue hope problem has been solved.
