### ISSUE TITLE
editMessageReplyMarkup and editMessageText methods are not working

### ISSUE THREAD

**Issue by iMasoud** [yagop/node-telegram-bot-api#175]
Hi,

I'm calling `editMessageReplyMarkup` method with these parameters:
```
var reply_markup = {"inline_keyboard":[[{"callback_data":"579a27fc082b43da63de74af,1","text":"1"},{"callback_data":"579a27fc082b43da63de74af,2","text":"2"}]]}
var message_id = 1789 //this is message_id property of a message which is sent by myBot with an inline reply markup

myBot.editMessageReplyMarkup(reply_markup, message_id)
```

And here is what i get as an error:
```
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"Bad Request: message identifier is not specified"}
    at /home/masoud/node.js/TCHBot/node_modules/node-telegram-bot-api/lib/telegram.js:186:17
    at tryCatcher (/home/masoud/node.js/TCHBot/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/masoud/node.js/TCHBot/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/masoud/node.js/TCHBot/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/masoud/node.js/TCHBot/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/masoud/node.js/TCHBot/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/masoud/node.js/TCHBot/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/masoud/node.js/TCHBot/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:419:13)
```

I have also tried replacing message_id with id property of the object that is presented by `callback_query` event and chat.id property of a message which is sent by myBot with an inline reply markup, and I got exactly the same error message.

I Also have the same problem with `editMessageText` method. Here is how I call it:
```
var message_id = 1789 //this is message_id property of a message which is sent by myBot with an inline reply markup
tchBot.editMessageText("edited! :)", message_id)
```

And here is what i get as an error:
```
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"Bad Request: Message text is empty"}
    at /home/masoud/node.js/TCHBot/node_modules/node-telegram-bot-api/lib/telegram.js:186:17
    at tryCatcher (/home/masoud/node.js/TCHBot/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/masoud/node.js/TCHBot/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/masoud/node.js/TCHBot/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/masoud/node.js/TCHBot/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/masoud/node.js/TCHBot/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/masoud/node.js/TCHBot/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/masoud/node.js/TCHBot/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:419:13)
```

In this case as well, I have tried to replace message_id with id property of the object that is presented by `callback_query` event and chat.id property of a message which is sent by myBot with an inline reply markup, and Again I got exactly the same error message.

I haven't tried `editMessageCaption` method yet.
So, can anyone tell me that is it my fault or something is wrong with the module?

Thank you very much for reading all this! :)

P.S: I have double checked all the parameters that i have passed to both methods.

**Comment by iMasoud** [comment]
Hey everyone,

Sorry for opening this issue! I was blind but now I see!

I have to pass message id as an object not as an integer or string!

Here is the true way to call editMessageTest for example:

```
var messahe_id = 1789
myBot.editMessageText("edited! :)", {message_id: messsge_id})
```
