### ISSUE TITLE
Unhandled rejection Error: 414 Request-URI Too Large

### ISSUE THREAD

**Issue by CTassisF** [yagop/node-telegram-bot-api#19]
Hello.

I think when the message sent using sendMessage is too long it triggers the following error:

```
<html>
<head><title>414 Request-URI Too Large</title></head>
<body bgcolor="white">
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>

    at /home/services/node/telegram/node_modules/node-telegram-bot-api/src/telegram.js:85:15
    at tryCatcher (/home/services/node/telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/services/node/telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/services/node/telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/services/node/telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/services/node/telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/services/node/telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/services/node/telegram/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:419:13)
```

The bot stops working after that.

Is there any way to fix this issue (and/or report it directly to Telegram team to enable bots to send longer messages)?

Thanks in advance.

**Comment by yagop** [comment]
As you said, it seems the message is too large to be sended. How long is it?
Maybe you should contact Telegram [bot support](telegram.me/BotSupport).

**Comment by CTassisF** [comment]
I will ask them what is the current size limit of a single message.

Anyway, can you please update node-telegram-bot-api to deal with this kind of error without entering some sort of "vegetative state" (as it currently does)?

Thanks in advance.

**Comment by SerjoPepper** [comment]
This bug is not related with telegram message size. It is related with GET request uri size restrictions http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.15
You should send all request with POST method to avoid this error
