### ISSUE TITLE
sendPhoto "414 Request-URI Too Large" when sending using body stream

### ISSUE THREAD

**Issue by ttpro1995** [yagop/node-telegram-bot-api#205]
Here is my code
```javascript
var TelegramBot = require('node-telegram-bot-api');
var request = require("request");

bot.onText(/\/randomcat/, function (msg, match) {
  var fromId = msg.from.id;
  var chatId = msg.chat.id;
  var resp = match[1];
  

  var test_link = "http://24.media.tumblr.com/tumblr_m3dsfmlcVq1r73wdao1_500.png";
  request(test_link, function (error, response, body) {
  if (!error && response.statusCode == 200) {
    bot.sendPhoto(chatId, body);
  }});
  

});


```
And the error

```
Unhandled rejection Error: 414 <html>
<head><title>414 Request-URI Too Large</title></head>
<body bgcolor="white">
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>

    at /home/ubuntu/workspace/meow_pic_bot/node_modules/node-telegram-bot-api/lib/telegram.js:219:17
    at tryCatcher (/home/ubuntu/workspace/meow_pic_bot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/meow_pic_bot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/ubuntu/workspace/meow_pic_bot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/ubuntu/workspace/meow_pic_bot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/ubuntu/workspace/meow_pic_bot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/ubuntu/workspace/meow_pic_bot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/workspace/meow_pic_bot/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by ttpro1995** [comment]
A workaround: save file, send, then delete

```javascript
bot.onText(/\/randomcat/, function (msg, match) {
  var fromId = msg.from.id;
  var chatId = msg.chat.id;
  var resp = match[1];
  var filename = "tmp_pic/"+microtime.now()+".png"; 
  
  var test_link = "http://24.media.tumblr.com/tumblr_m3dsfmlcVq1r73wdao1_500.png";
  
  /*
  request(test_link, function (error, response, body) {
  if (!error && response.statusCode == 200) {
    bot.sendPhoto(chatId, body);
  }});
  */
  
  // download file, send, then delete
  request(test_link).pipe(fs.createWriteStream(filename).on('close', function() {
  // done download file
  bot.sendPhoto(chatId, filename).then(function(){
  // photo sent, deleted temp file
    fs.unlinkSync(filename);
  });
}));
  
  console.log(link);
});
```

**Comment by GochoMugo** [comment]
As documented in [request's homepage](https://github.com/request/request#requestoptions-callback):

> The third is the response body (`String` or `Buffer`, or JSON object if the `json` option is supplied)

From your 1st code [above](https://github.com/yagop/node-telegram-bot-api/issues/205#issue-182519249), the body is a string! To confirm this, try:

```js
typeof body === "string"; // this will return 'true'
```

Therefore when calling `bot.sendPhoto()`, your `body` argument is assumed to be a `file_id` [here](https://github.com/yagop/node-telegram-bot-api/blob/58566d2df5146611a6a3e6140ca616403d24a20e/src/telegram.js#L346). It is therefore attached to the querystring ([here](https://github.com/yagop/node-telegram-bot-api/blob/58566d2df5146611a6a3e6140ca616403d24a20e/src/telegram.js#L368)). Since the `body` of your image is quite large, it results in a rather unusually large request URI.

If you wanted to get a buffer from `request`, please [see their documentation](https://github.com/request/request#requestoptions-callback) on how to do so. Specifically the `encoding` option!

**Comment by GochoMugo** [comment]
Also, see issue #171 on how to use streams with the `request` module.
