### ISSUE TITLE
Unable to get local issuer certificate when trying to getUpdates

### ISSUE THREAD

**Issue by evan3334** [yagop/node-telegram-bot-api#234]
Whenever I try to call `getUpdates()` on a TelegramBot object, it throws an error in the console:
``` 
Unhandled rejection RequestError: Error: unable to get local issuer certificate
    at new RequestError (<redacted>\node_modules\node-telegram-bot-api\node_modules\request-promise\lib\errors.js:11:15)
    at Request.RP$callback [as _callback] (C:\Users\18Straw.Evan\Desktop\NodeJS\node_modules\node-telegram-bot-api\node_modules\request-promise\lib\rp.js:60:32)
    at self.callback (C:\Users\18Straw.Evan\Desktop\NodeJS\node_modules\node-telegram-bot-api\node_modules\request\request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\18Straw.Evan\Desktop\NodeJS\node_modules\node-telegram-bot-api\node_modules\request\request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
This error will also be spammed repeatedly if I enable polling.
I'm not sure why this happens, I've never needed a certificate of any kind on any other computer. It could be caused by a proxy screwing with HTTPS, I **am** on a school network which uses OpenDNS for network censorship/category blocking but I've managed to run this successfully on another computer behind this same network so I don't know why only this computer is having an issue.

Does anyone have any advice or ideas on how to fix this? Any help would be appreciated.

_PS. I don't have admin privileges on this Windows computer, i'm running a local install of NodeJS on a local path._

**Comment by yagop** [comment]
Can you run it with debug and try to connect to the URL? Something like:

DEBUG=* node index.js

**Comment by evan3334** [comment]
I'm no longer on that pc, I'll have to test later sorry

**Comment by evan3334** [comment]
I'm not sure what the equivalent of that command would be on Windows...
I tried running `node debug bottest.js` and it gave the same error with no extra information.

I bet it's probably just the network censorship software, it always messes up HTTPS when using web browsers... I don't have this problem on any machine not monitored by this software. I have a server I can SSH into that's not on the network, I can do this from there.

Thanks for the help!

**Comment by yagop** [comment]
Its just environment variables, I think it can be [set]((http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows)) on windows by:

```
set DEBUG=*
node bottest.js
```

But I don't code on Windows. [Insert rage against Winodws here]

**Comment by evan3334** [comment]
Oh I don't either lol I just happen to be on a Windows computer right now.

Running that command produced this output:
```
C:\Users\<redacted>\Desktop\NodeJS>set DEBUG=*

C:\Users\<redacted>\Desktop\NodeJS>node bottest.js
  node-telegram-bot-api HTTP request: {"form":{},"url":"https://api.telegram.org/bot306589704:AAFzSl45lqZqc4psSWJA0EpRjTiGIsvSJys/getUpdates","simple":false,"resolveWithFullResponse":true} +0ms
Unhandled rejection RequestError: Error: unable to get local issuer certificate
    at new RequestError (C:\Users\<redacted>\Desktop\NodeJS\node_modules\request-promise\lib\errors.js:11:15)
    at Request.RP$callback [as _callback] (C:\Users\<redacted>\Desktop\NodeJS\node_modules\request-promise\lib\rp.js:60:32)
    at self.callback (C:\Users\<redacted>\Desktop\NodeJS\node_modules\request\request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\<redacted>\Desktop\NodeJS\node_modules\request\request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)```

**Comment by yagop** [comment]
As you said, there is an issue whith the certificate: `Unhandled rejection RequestError: Error: unable to get local issuer certificate`. Maybe you can bypass the error by setting this environment variable:
```
set NODE_TLS_REJECT_UNAUTHORIZED = "0"
```

**Comment by yagop** [comment]
You should re-generate the bot token, it was exposed you your comment (I edited it.)

**Comment by evan3334** [comment]
Ok, I'll try that when I get back on that certain PC. I think if it doesn't work though I can just SSH into my server to work around it.
As for the token, I've regenerated it. Thanks for catching that, I was so focused on redacting my username and didn't even remember it was supposed to be secret XD
