### ISSUE TITLE
Unhandled rejection RequestError: Error: connect ETIMEDOUT 149.154.167.200:443

### ISSUE THREAD

**Issue by Lord-Protector** [yagop/node-telegram-bot-api#237]
I can't use my bot with real users, because if they send me two (or even one) requests simultaneously, bot can't send them stickers (I generate server-side infographics via stickers / photos in 600 x 400 resolution). So I get this error:
```
Unhandled rejection RequestError: Error: connect ETIMEDOUT 149.154.167.200:443
    at new RequestError (/home/savely/overwatch-telegram-bot/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/home/savely/overwatch-telegram-bot/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/home/savely/overwatch-telegram-bot/node_modules/request/request.js:186:22)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/savely/overwatch-telegram-bot/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
I am using webhooks, so I can't increase timeout or something like this. Server is in the west of Russia.

**Comment by GochoMugo** [comment]
A possible cause of error `ETIMEDOUT` is that the Telegram servers closed the connection, maybe due to slow connection to your server. You may want to [check out this thread](https://groups.google.com/forum/#!topic/redis-db/vfums8vxd3E) discussing this error (although it is around Redis, but the information is still valuable!). If you get it to work, please post what you did here, so we can close this issue.

**Comment by Lord-Protector** [comment]
I move my VPS in France (before it was in Russia). Now all works nice.
But it's only workaround I think.

**Comment by GochoMugo** [comment]
Closing this as we have hit rock bottom with this issue! Thanks @Lord-Protector for using this library!
