### ISSUE TITLE
resend when ETIMEDOUT and set shorter timeout 

### ISSUE THREAD

**Issue by warbaque** [yagop/node-telegram-bot-api#303]
create new bot:
`var tg = new Telegram(BOT_TOKEN, {polling: true});`

send message:
`tg.sendMessage(CHAT_ID, msg);`

And quite often after sending (after waiting for 2 minutes) I get timeout error:
```
Unhandled rejection RequestError: Error: connect ETIMEDOUT 149.154.167.197:443
    at new RequestError (/mnt/storage/data/git/teleirc_fruitiex/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/mnt/storage/data/git/teleirc_fruitiex/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/mnt/storage/data/git/teleirc_fruitiex/node_modules/node-telegram-bot-api/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/mnt/storage/data/git/teleirc_fruitiex/node_modules/node-telegram-bot-api/node_modules/request/request.js:186:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/mnt/storage/data/git/teleirc_fruitiex/node_modules/node-telegram-bot-api/node_modules/request/request.js:845:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickCallback (node.js:372:17)
```

How should I handle resend?
I would like to resend message if sending didn't succeed in for example 15 seconds.

I'm currently testing with something like this:
```
var sendMessage = function(msg) {
    console.log('>> relaying to TG:', msg);
    tg.sendMessage(CHAT_ID, msg).catch(error => {
        console.log("   resending message: " + msg);
        sendMessage('[resend test] ' + msg)
    });
};

sendMessage('this is a message');
```

Is there a better way and can I set timeout shorter than 2 minutes?

**Comment by warbaque** [comment]
Setting timeout for promise seems to work, but might send duplicate messages if original message goes through after 15 sec timeout.
```
var sendMessage = function(msg) {
    console.log('>> relaying to TG:', msg);
    tg.sendMessage(CHAT_ID, msg).timeout(15000).then(res => {
        console.log("success : " + msg);
    }).catch(error => {
        console.log("failed  : " + msg);
        sendMessage(msg);
    });
};
```
