### ISSUE TITLE
Sending documents by HTTP URL returns 400 Bad Request

### ISSUE THREAD

**Issue by pedrofracassi** [yagop/node-telegram-bot-api#314]
### Expected Behavior

I'm trying to send a GIF to a channel using `sendDocument`, with the chat ID and the document's URL

### Actual Behavior

I'm getting a 400 error, that says "Bad Request: there is no document in the request"

### Steps to reproduce the Behavior

```javascript
bot.onText(/\/link (.+)/, (msg, match) => {
  const chatId = msg.chat.id;
  const resp = match[1];
  bot.sendDocument(chatId, match);
});
```

And then send /link + the document's http link to the bot on a private chat.

**Comment by GochoMugo** [comment]
Your code has a small typo, you are doing `bot.sendDocument(chatId, match)` instead of `bot.sendDocument(chatId, resp)`.

PS: Consider that the link may NOT be pointing to a GIF, thus the `sendDocument()` call may fail in such a scenario.

**Comment by pedrofracassi** [comment]
The code I posted was an example, I tried hardcoding the links to the bot, and it didn't work either

**Comment by pedrofracassi** [comment]
And also, sending audioless .mp4 links via the HTTP API (by hand, I mean) worked fine.

**Comment by GochoMugo** [comment]
Can you provide us with links that don't work with the method?

**Comment by pedrofracassi** [comment]
Used this exact code:
```javascript
bot.onText(/\/link (.+)/, (msg, match) => {
  const chatId = msg.chat.id;
  const resp = match[1];
  bot.sendDocument(chatId, resp);
});
```

and sent this exact command:

`/link http://i.imgur.com/nho74sk.mp4`

got this exact error

```
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: there is no document in the request
    at BaseError (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\node-telegram-bot-api\src\errors.js:10:5)
    at TelegramError (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\node-telegram-bot-api\src\errors.js:56:5)
    at request.then.err (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\node-telegram-bot-api\src\telegram.js:181:15)
    at tryCatcher (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

Unhandled rejection Error: ETELEGRAM: 400 Bad Request: wrong file identifier/HTTP URL specified
    at BaseError (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\node-telegram-bot-api\src\errors.js:10:5)
    at TelegramError (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\node-telegram-bot-api\src\errors.js:56:5)
    at request.then.err (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\node-telegram-bot-api\src\telegram.js:181:15)
    at tryCatcher (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Pichau\Documents\GitHub\thegifmachine\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

**Comment by GochoMugo** [comment]
Do you mind opening a new, separate issue for this? Please provide us with the example URLs, like the one you stated above, that cause the method to fail.
