### ISSUE TITLE
this._webHook.open is not a function

### ISSUE THREAD

**Issue by Besatnias** [yagop/node-telegram-bot-api#327]
I'm getting this error when I try to run webhook with [this code](https://github.com/Besatnias/code-dumpster/blob/master/ngroktest.js), which is a derivate of [this code](https://github.com/kamikazechaser/ThorsHammer/blob/ngrok/core/telegram.js):
```
C:\Users\venta\projects\node\node_modules\node-telegram-bot-api\lib\telegram.js:
304
    return this._webHook.open();
                         ^

TypeError: this._webHook.open is not a function
    at TelegramBot.openWebHook (C:\Users\venta\projects\node\node_modules\node-telegram-bot-api\lib\telegram.js:304:26)
    at new TelegramBot (C:\Users\venta\projects\node\node_modules\node-telegram-bot-api\lib\telegram.js:93:14)
    at Object.<anonymous> (C:\Users\venta\projects\node\ngroktest.js:29:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
```

I have no idea what it means or how to fix it or reproduce it with simple code, so I'll just leave it to you.

**Comment by yagop** [comment]
`_webHook` is not intended to be accessed that way. `_` means that is private.

If you want to create a webHook, you should provide TelegramBot [constructor](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#new_TelegramBot_new) webHook options.

**Comment by GochoMugo** [comment]
**!CLOSE**

---

why: Since we can **not** reproduce, we can neither confirm this bug nor fix it. Sorry, please provide us with more information (for reproduction), if you wish to re-open the issue.
