### ISSUE TITLE
Webhook issue

### ISSUE THREAD

**Issue by cisbeo** [yagop/node-telegram-bot-api#37]
Hi

I generated certificate 
openssl genrsa -out key.pem 2048
openssl req -new -sha256 -key key.pem -out crt.pem

but my bot scratch with 

_tls_common.js:132
      c.context.setCert(options.cert);
                ^
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:132:17)
    at Server (_tls_wrap.js:598:25)
    at new Server (https.js:36:14)
    at Object.exports.createServer (https.js:56:10)
    at new TelegramBotWebHook (/Users/cedricboussicaud/projects/packbot/node_modules/node-telegram-bot-api/src/telegramWebHook.js:23:29)
    at new TelegramBot (/Users/cedricboussicaud/projects/packbot/node_modules/node-telegram-bot-api/src/telegram.js:53:21)
    at Object.<anonymous> (/Users/cedricboussicaud/projects/packbot/app.js:20:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Thank you for helping

**Comment by cisbeo** [comment]
just a problem generating my certificate. Here command line works on mac osx :+1: openssl req -newkey rsa:2048 -sha256 -nodes -keyout YOURPRIVATE.key -x509 -days 365 -out YOURPUBLIC.pem -subj "/C=FR/ST=Paris/L=Marly/O=Example Brooklyn Company/CN=packbot"
Generating a 2048 bit RSA private key

**Comment by bogdyak** [comment]
Thank you!
It helps me
