### ISSUE TITLE
inline query error with the type of results

### ISSUE THREAD

**Issue by abbddo** [yagop/node-telegram-bot-api#382]
this is my code

```
bot.on('inline_query', (query) => {

	var id = query.from.id;

	var results = [];

	var link = "t.me/saraha4bot?start=" + id; 

	results.push(link);

	bot.answerInlineQuery(query.id, results);
});
```

when I run it I got this error 
`
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: inline query result must be an object
    at BaseError (C:\Users\NS\babbot\node_modules\node-telegram-bot-api\src\errors.js:10:5)
    at TelegramError (C:\Users\NS\babbot\node_modules\node-telegram-bot-api\src\errors.js:56:5)
    at request.then.err (C:\Users\NS\babbot\node_modules\node-telegram-bot-api\src\telegram.js:181:15)
    at tryCatcher (C:\Users\NS\babbot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\NS\babbot\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\NS\babbot\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\NS\babbot\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\NS\babbot\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\NS\babbot\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\NS\babbot\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\NS\babbot\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
`

I've tried to change it to an object but when I change the
 `results`  variable to object another error pops and says
 `inline query result must be an array`

**Comment by phrozen** [comment]
What was your solution to this? I'm stuck trying to send the results to the inline query and I get the same errors.
