### ISSUE TITLE
kickchatMember issue

### ISSUE THREAD

**Issue by Snackb0ne** [yagop/node-telegram-bot-api#385]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

It should return false if the member has not been banned when using .kickChatMember
(The member is an admin so it should return something)

### Actual Behavior

It returns True even if the member(an admin) is still there in the group, and after the promise has been fulfilled , it returns the error, 

Unhandled rejection Error: ETELEGRAM: 400 Bad Request: user is an administrator of the chat
    at request.then.resp (C:\Users\Laxmi Narayan\Desktop\Shotz\Shotz-For-Telegram\node_modules\node-telegram-bot-api\src\telegram.js:181:15)
    at tryCatcher (C:\Users\Laxmi Narayan\Desktop\Shotz\Shotz-For-Telegram\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Laxmi Narayan\Desktop\Shotz\Shotz-For-Telegram\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Laxmi Narayan\Desktop\Shotz\Shotz-For-Telegram\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Laxmi Narayan\Desktop\Shotz\Shotz-For-Telegram\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Laxmi Narayan\Desktop\Shotz\Shotz-For-Telegram\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Laxmi Narayan\Desktop\Shotz\Shotz-For-Telegram\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Laxmi Narayan\Desktop\Shotz\Shotz-For-Telegram\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Laxmi Narayan\Desktop\Shotz\Shotz-For-Telegram\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

### Steps to reproduce the Behavior

Heres the code that causes this error

    tgresolve(settings.BotToken, args[1], (err, user) =>{
      if(err){
        shotz.sendMessage(msg.chat.id, err.message)
      }
      if(shotz.kickChatMember(msg.chat.id, user.id)) {
        shotz.sendMessage(msg.chat.id, `${user.username} has been BANNED!`)
      }

> Feature Request

I have:

* searched for such a feature request (https://github.com/yagop/node-telegram-bot-api/labels/enhancement) and found none

### Example

> Question

**Comment by GochoMugo** [comment]
The [TelegramBot#kickChatMember(chatId, userId)](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#TelegramBot+kickChatMember) returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), not a Boolean. Please read through the [documentation](https://github.com/yagop/node-telegram-bot-api#documentation) to learn how to use the library.

Feel free to elaborate your issue further, if the above does **not** suffice.
