### ISSUE TITLE
forwardMessage not working after Bot API 3.4 release

### ISSUE THREAD

**Issue by zakeri** [yagop/node-telegram-bot-api#441]
I observed that after new bot API 3.4 release this code gives exception:

`msg = await bot.forwardMessage(my_channel1_id, my_channel2_id, my_message_id);`

Error: ETELEGRAM: 400 Bad Request: message to forward not found
    at request.then.resp (/home/hassan/telegram-ads/node_bot/node_modules/node-telegram-bot-api/src/telegram.js:213:15)
    at tryCatcher (/home/hassan/telegram-ads/node_bot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/hassan/telegram-ads/node_bot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/hassan/telegram-ads/node_bot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/hassan/telegram-ads/node_bot/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/hassan/telegram-ads/node_bot/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/hassan/telegram-ads/node_bot/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/hassan/telegram-ads/node_bot/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/hassan/telegram-ads/node_bot/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

Any clue on why I am seeing this is appreciated.

**Comment by mosyflasher** [comment]
I have the same issue, any solution?

**Comment by GochoMugo** [comment]
As far as I can tell, this is an issue with Telegram Bot API itself, and **not** with this library. Ensure you that the message you are trying to forward does exist (as the error message explains). However, if this is still an issue, please contact Bot Support for more help. Please keep us updated so that we can responsibly close this issue.

**Comment by lifehome** [comment]
Hi, by using your line of code, I can confirm it is working right now. Have you enlisted the bot as admin in those channels you prefer to send? You will also need to enlist the bot as admin if the source channel is private, otherwise just use a string with a `@` as prefix, such as `@username`.

**Comment by Arjun-M** [comment]
The same issue happens with me also .
But I have noticed that bot forwarded message successfully and still logs "ETELEGRAM: 400 Bad Request: message to forward not found"
