### ISSUE TITLE
Socket Hang up

### ISSUE THREAD

**Issue by DaniyalGeek** [yagop/node-telegram-bot-api#464]
error: { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }

Can any one help me to understand why this happening

**Comment by saeedhei** [comment]
+1

**Comment by schizobulia** [comment]
+1

**Comment by tsofist** [comment]
+1 :disappointed: 
Catch this only on `sendDocument` call

**Comment by Knoot** [comment]
In my case it was
`const stream = fs.createReadStream(filename)`
It was enough to close the stream after sending and the error disappeared
`bot.sendPhoto(msg.chat.id, stream).finally(() => stream.close())`

**Comment by yagop** [comment]
The legacy HTTP implementation was replaced in v2. Connection resets are now exposed as `NetworkError` and transient failures are retried automatically. Node file uploads created with `fromPath()` can also be replayed safely across retries. Please open a new issue with a minimal v2 reproduction if a connection reset remains reproducible. Closing as completed by v2.
