### ISSUE TITLE
Unhandled 'error' event  after some hours of running

### ISSUE THREAD

**Issue by dtsrwnis** [yagop/node-telegram-bot-api#47]
Works perfect but after some hours in my raspberry i take this error every time!

![bromh7b](https://cloud.githubusercontent.com/assets/9705923/11206928/c1635218-8d1a-11e5-89e9-d99368dcff74.png)

**Comment by koalazak** [comment]
Similar problem here. With basic example:
```javascript
var bot = new TelegramBot(token, { polling: true });
bot.on('message', function (msg) {
    console.log(msg)
});
```
After some hours of running the bot stops receive messages. And i can see a stablished connection to the telegram server IP thats never disconnect. Then hours later get the message:
```
Unhandled rejection Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at TLSSocket.socketOnEnd (_http_client.js:300:23)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```
Restarting the process the bot starts receive old messages again.

Its this issue related to polling?

Any luck fixing this?

**Comment by BrOrlandi** [comment]
Have a similar problem here trying to send messages over the API.
```
Unhandled rejection Error: 500 
    at /app/node_modules/node-telegram-bot-api/src/telegram.js:111:15
    at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](/app/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by BrOrlandi** [comment]
I think sometimes the API have problems, I'm testing with python (eternnoir/pyTelegramBotAPI) and getting error on sending photo and audio files.

**Comment by GochoMugo** [comment]
@dtsrwnis: you seem to be using a different node module, this library is named `node-telegram-bot-api` and **not** `node-telegram-bot`!

@koalazak: does your problem still persist?

**Comment by koalazak** [comment]
@GochoMugo let me check again with latest...

**Comment by GochoMugo** [comment]
Issue went too stale...

**Comment by koalazak** [comment]
sorry, i check that and works now :p
