### ISSUE TITLE
sendPhoto issue

### ISSUE THREAD

**Issue by christophetd** [yagop/node-telegram-bot-api#49]
Hi, 

I am facing issues with the sendPhoto method. 

```javascript
// line 83
bot.sendPhoto(msg.chat.id, 'xkcd.png', { caption: "hi" } ) 
```

I am getting the following error :

```
Unhandled rejection TypeError: undefined is not a function
  at FormData._multiPartHeader (C:\Users\Christophe\workspace\thousandbot\node_modules\request\node_modules\form-data\lib\form_data.js:185:47)
  at FormData.append (C:\Users\Christophe\workspace\thousandbot\node_modules\request\node_modules\form-data\lib\form_data.js:42:21)
  at appendFormValue (C:\Users\Christophe\workspace\thousandbot\node_modules\request\request.js:337:21)
  at Request.init (C:\Users\Christophe\workspace\thousandbot\node_modules\request\request.js:350:11)
  at new Request (C:\Users\Christophe\workspace\thousandbot\node_modules\request\request.js:140:8)
  at request (C:\Users\Christophe\workspace\thousandbot\node_modules\request\index.js:55:10)
  at tryCatcher (C:\Users\Christophe\workspace\thousandbot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\main\util.js:26:23)
  at ret (<anonymous>:14:23)
  at [object Object].TelegramBot._request (C:\Users\Christophe\workspace\thousandbot\node_modules\node-telegram-bot-api\src\telegram.js:101:10)
  at [object Object].TelegramBot.sendPhoto (C:\Users\Christophe\workspace\thousandbot\node_modules\node-telegram-bot-api\src\telegram.js:265:15)
  at Object.callback (C:\Users\Christophe\workspace\thousandbot\app.coffee:83:9)
  at C:\Users\Christophe\workspace\thousandbot\node_modules\node-telegram-bot-api\src\telegram.js:87:15
  at Array.forEach (native)
  at [object Object].TelegramBot._processUpdate (C:\Users\Christophe\workspace\thousandbot\node_modules\node-telegram-bot-api\src\telegram.js:82:32)
  at C:\Users\Christophe\workspace\thousandbot\node_modules\node-telegram-bot-api\src\telegramPolling.js:39:12
  at Array.forEach (native)
  at C:\Users\Christophe\workspace\thousandbot\node_modules\node-telegram-bot-api\src\telegramPolling.js:33:13
  at tryCatcher (C:\Users\Christophe\workspace\thousandbot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\main\util.js:26:23)
  at Promise._settlePromiseFromHandler (C:\Users\Christophe\workspace\thousandbot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\main\promise.js:507:31)
  at Promise._settlePromiseAt (C:\Users\Christophe\workspace\thousandbot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\main\promise.js:581:18)
  at Promise._settlePromises (C:\Users\Christophe\workspace\thousandbot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\main\promise.js:697:14)
  at Async._drainQueue (C:\Users\Christophe\workspace\thousandbot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\main\async.js:123:16)
  at Async._drainQueues (C:\Users\Christophe\workspace\thousandbot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\main\async.js:133:10)
  at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Christophe\workspace\thousandbot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\main\async.js:15:14)
  at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Additional remarks:
- The bot is correctly running and set up
- The file xkcd.png is in the same directory as my script. It is a valid image with correct access rights
- I have tried to replace `"xkcd.png"` with
  - `"./xkcd.png"`
  - `fs.createReadStream("xkcd.png")`
  - `__dirname + "/xkcd.png"`
  - `__dirname + "\\xkcd.png"` (I am on windows)
  - `__dirname.replace(/\//g, '/') + "/xkcd.png"`

But any of these forms gives me the exact same error.
- `msg.chat.id` is a valid telegram chat id

Any help appreciated!

Thanks

**Comment by yagop** [comment]
Really weird error. Tests are [passing](https://ci.appveyor.com/project/yagop/node-telegram-bot-api/branch/master) on Windows. And `__dirname + "/xkcd.png"` is the same as  https://github.com/yagop/node-telegram-bot-api/blob/master/test/index.js#L165.

Which NodeJS and request module (`npm ls request`) are you using?

**Comment by christophetd** [comment]
Thank you for your answer. I am using request version 2.66.0.

**Comment by yagop** [comment]
And NodeJS?

**Comment by christophetd** [comment]
Node v0.12.5

**Comment by christophetd** [comment]
Somehow I managed to fix this. Quite unsure of how I did it, though... Thank you for your help.

**Comment by yagop** [comment]
![a6pswtfcuai7n-5](https://cloud.githubusercontent.com/assets/5002453/11340457/3c49a01c-91fe-11e5-86cf-97d7a055e040.jpg)
