### ISSUE TITLE
bot.sendPhoto is not working from yesterday . 

### ISSUE THREAD

**Issue by droidmanspace** [yagop/node-telegram-bot-api#493]
bot.onText(/\/p/, (msg, match) => {
  const chatId = msg.chat.id;
  fs.readFile('bike.png', function (err, data ) {
    if (err){
            console.log(err);
           }
           else{
             bot.sendPhoto(chatId,data)
           }
  });

I  tried all the ways, but I can send the image using specifying URL instead of buffer.

ERROR
~~~~~
Unhandled rejection RequestError: TypeError: The header content contains invalid characters
    at new RequestError (/root/nodeserver/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/root/nodeserver/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/root/nodeserver/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/root/nodeserver/node_modules/request/request.js:186:22)
    at emitOne (events.js:120:20)
    at Request.emit (events.js:210:7)
    at Request.start (/root/nodeserver/node_modules/request/request.js:750:10)
    at Request.write (/root/nodeserver/node_modules/request/request.js:1498:10)
    at FormData.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:115:13)
    at FormData.emit (events.js:210:7)
    at FormData.CombinedStream.write (/root/nodeserver/node_modules/combined-stream/lib/combined_stream.js:118:8)
    at FormData.CombinedStream._pipeNext (/root/nodeserver/node_modules/combined-stream/lib/combined_stream.js:106:8)
    at FormData.CombinedStream._getNext (/root/nodeserver/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream.resume (/root/nodeserver/node_modules/combined-stream/lib/combined_stream.js:134:10)
    at FormData.CombinedStream.pipe (/root/nodeserver/node_modules/combined-stream/lib/combined_stream.js:64:8)
    at end (/root/nodeserver/node_modules/request/request.js:528:22)
    at FormData.<anonymous> (/root/nodeserver/node_modules/request/request.js:572:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Unhandled rejection RequestError: TypeError: The header content contains invalid characters
    at new RequestError (/root/nodeserver/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/root/nodeserver/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/root/nodeserver/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/root/nodeserver/node_modules/request/request.js:186:22)
    at emitOne (events.js:120:20)
    at Request.emit (events.js:210:7)
    at Request.start (/root/nodeserver/node_modules/request/request.js:750:10)
    at Request.write (/root/nodeserver/node_modules/request/request.js:1498:10)
    at FormData.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:115:13)
    at FormData.emit (events.js:210:7)
    at FormData.CombinedStream.write (/root/nodeserver/node_modules/combined-stream/lib/combined_stream.js:118:8)
    at FormData.CombinedStream._pipeNext (/root/nodeserver/node_modules/combined-stream/lib/combined_stream.js:106:8)
    at FormData.CombinedStream._getNext (/root/nodeserver/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream.resume (/root/nodeserver/node_modules/combined-stream/lib/combined_stream.js:134:10)
    at FormData.CombinedStream.pipe (/root/nodeserver/node_modules/combined-stream/lib/combined_stream.js:64:8)
    at end (/root/nodeserver/node_modules/request/request.js:528:22)
    at FormData.<anonymous> (/root/nodeserver/node_modules/request/request.js:572:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by droidmanspace** [comment]
**After update the node-telegram-bot-api to v0.30.0** , 
```
bot.onText(//p/, (msg, match) => {
const chatId = msg.chat.id
var file = fs.readFileSync('bike.png')
const fileOpts = {
    filename : 'bike',
    contentType : 'image/png'
  }
     bot.sendPhoto(chatId,file,{},fileOpts)
})
```
**LOG :**
```
node-telegram-bot-api deprecated In the future, content-type of files you send will default to "application/octet-stream". See https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md#sending-files for more information on how sending files has been improved and on how to disable this deprecation message altogether. app.js:53:17
(node:2832) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EFATAL: TypeError: The header content contains invalid characters
(node:2832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by droidmanspace** [comment]
Its make conflict with node-rest-client . how to solve it ?

**Comment by ildevelop** [comment]
@droidmanspace  it`s work good!
 Now how i can take img from user ??

**Comment by danielperez9430** [comment]
> @droidmanspace it`s work good! Now how i can take img from user ??

You have a method "`getUserProfilePhotos`"
