### ISSUE TITLE
Save user's voice message;

### ISSUE THREAD

**Issue by eof273** [yagop/node-telegram-bot-api#510]
> Question

Hello. Sorry for stupid question, but: how I can save user's voice message?
For this code:

    tBot.on('voice', (msg)=>{
      tBot.getFile(msg.voice.file_id, () => {
        //...
      });
    });

I've got error:

>Unhandled rejection Error: ETELEGRAM: 400 Bad Request: wrong persistent file id

Full stack trace:

    Unhandled rejection Error: ETELEGRAM: 400 Bad Request: wrong persistent file id
        at BaseError (D:\dbp\bot1\node_modules\node-telegram-bot-api\src\errors.js:10:5)
        at TelegramError (D:\dbp\bot1\node_modules\node-telegram-bot-api\src\errors.js:62:5)
        at request.then.err (D:\dbp\bot1\node_modules\node-telegram-bot-api\src\telegram.js:280:15)
        at tryCatcher (D:\dbp\bot1\node_modules\bluebird\js\release\util.js:16:23)
        at Promise._settlePromiseFromHandler (D:\dbp\bot1\node_modules\bluebird\js\release\promise.js:512:31)
        at Promise._settlePromise (D:\dbp\bot1\node_modules\bluebird\js\release\promise.js:569:18)
        at Promise._settlePromise0 (D:\dbp\bot1\node_modules\bluebird\js\release\promise.js:614:10)
        at Promise._settlePromises (D:\dbp\bot1\node_modules\bluebird\js\release\promise.js:693:18)
        at Async._drainQueue (D:\dbp\bot1\node_modules\bluebird\js\release\async.js:133:16)
        at Async._drainQueues (D:\dbp\bot1\node_modules\bluebird\js\release\async.js:143:10)
        at Immediate.Async.drainQueues (D:\dbp\bot1\node_modules\bluebird\js\release\async.js:17:14)
        at runCallback (timers.js:672:20)
        at tryOnImmediate (timers.js:645:5)
        at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by justfry** [comment]
Same trouble, but with getting documents.

**Comment by eof273** [comment]
@justfry 
First of all - thanks, for reminded me about this task;
Second - shame on me... You must use promise instead of callback:

```javascript
tBot.getFile(voiceId).then((resp) => {
  /*
  {
    file_id : 'YOUR_FILE_ID',
    file_size : 6666,
    file_path : 'YOUR_FILE_PATH'
  }
  */
});
```
and
```javascript
tBot.getFileLink(voiceId).then((a) => {
  /*
  'https://api.telegram.org/file/botYOUR_TOKEN/YOUR_FILE_PATH'
  */
});
```

**Comment by justfry** [comment]
@eof273 it's works! Thanks!

**Comment by DsJohn** [comment]
but this work only for 1 voice message, how to make it work for each sent?
