### ISSUE TITLE
SyntaxError on Raspberry Pi

### ISSUE THREAD

**Issue by dj2bee** [yagop/node-telegram-bot-api#53]
Hi!
I tried to use my Raspberry Pi Model B (running `raspbian` and `node v4.2.3`) as telegram-bot but it won't work. When running the bot on Windows or Mac everything works just fine.

1) Here's the error I am getting when sending a message via bot.sendMessage():

```
Unhandled rejection SyntaxError: Unexpected token <
    at Object.parse (native)
    at /home/development/DukesFotobot/node_modules/node-telegram-bot-api/src/telegram.js:113:23
    at tryCatcher (/home/development/DukesFotobot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/development/DukesFotobot/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/development/DukesFotobot/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/development/DukesFotobot/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/development/DukesFotobot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/development/DukesFotobot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/development/DukesFotobot/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

2) In addition to not being able to send messages, the bot won't even receive messages (onText is not being called).

If you have any ideas on this, I would be very thankful for a reply.

Cheers,
dj2bee

**Comment by yagop** [comment]
This error happens when bot is unable to parse the JSON data received from Telegram, nothing related with Raspberry Pi.

**Comment by dj2bee** [comment]
Okay, thanks for the reply. Then I have to do some further investigations, because I only get the error when running the code on my Raspberry Pi.

**Comment by yagop** [comment]
Raspberry is behind a proxy / firewall?

**Comment by dj2bee** [comment]
Yes, it is behind a firewall, but the firewall is cofigured correctly.

`curl -X POST -d @payload.txt https://api.telegram.org/botXXX/sendMessage --header "Content-Type:application/json"`
returns
`{"ok":true,"result":{"message_id":420,"from":{"id":1234567,"first_name":"xyz","username":"xyz"},"chat":{"id":1234567,"first_name":"xyz","last_name":"xyz","username":"xyz","type":"private"},"date":1452028611,"text":"foo bar"}}`

**Comment by dj2bee** [comment]
I solved this one on my own.
The error occured when reading the token from an external textfile using ```fs.readFileSync(...)```: For no reason a ```\n``` was added to the file which resulted in a bad URL.
I simply split the file by ```\n``` and select the first entry of the array:

```
var tgToken = fs.readFileSync('./token.txt', 'utf8').split('\n')[0];
```

On Windows and Mac it works fine without doing the split-trick ;)
