### ISSUE TITLE
Get file erroring

### ISSUE THREAD

**Issue by Extra-Mental** [yagop/node-telegram-bot-api#561]
Trying to get a photo that has been sent in a chat leads to an error that i cant seem to figure out how to resolve.

my code:

```javascript
const Bot = require('telegram-bot-api');

const token = "X";

var api = new Bot({
        token: token,
        updates: {
        	enabled: true
    }
});

api.on('message', function(Data){
  var Caption = Data.caption;
  if(Caption){
    var ImgID = Data.photo[Data.photo.length-1].file_id; if(!ImgID){return;};//best quality photo
    api.getFile(ImgID).then(function(resp){
      console.log(resp)
    });
  }

});
```

Error code with removed personal dir names:

```
X\node_modules\bluebird\js\release\async.js:61
        fn = function () { throw arg; };
                           ^
StatusCodeError: 400 - [object Object]
    at new StatusCodeError (X\node_modules\telegram-bot-api\node_modules\request-promise\lib\errors.js:26:15)
    at Request.RP$callback [as _callback] (X\node_modules\telegram-bot-api\node_modules\request-promise\lib\rp.js:68:32)
    at Request.self.callback (X\node_modules\request\request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (X\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (X\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by sidelux** [comment]
I think you have something broken in libraries, maybe.

0. Your bot works if you send a simple message instead of image or any other function?
Btw try:
1. to change "api" var name (maybe it conflicts with bluebird vars...)
2. to reinstall all modules
3. to add this code at top of the file:
```
process.on('unhandledRejection', function (error, p) {
	console.log("unhandledRejection: " + error.message);
});
```

**Comment by Extra-Mental** [comment]
Oh i just noticed im using a different API, my bad, the names are too similar
