### ISSUE TITLE
Send image from Telegram to Discord

### ISSUE THREAD

**Issue by ThiPereira** [yagop/node-telegram-bot-api#599]
> Question

I have 2 bots running: one Telegram Bot and one Discord Bot...
I need get an image from my TG channel and forward to my Discord channel...
Anyone knows how to do this?

Best,
Thiago

**Comment by sidelux** [comment]
I think you can do something like this:
(assuming that two bots are on the same server)
1. Telegram bot save image in a folder when received from bot
2. Discord bot looking in that folder and grab image, then delete it

I don't know how to program for discord, but telegram side can be like:

```
var http = require('http');
var fs = require('fs');

bot.on('message', function (message) {
    if (message.photo != undefined){
        bot.getFile(message.photo[0].file_id).then(function (fileData) {
            var downloadUrl = fileData.file_path;
            var randomFileName = "downloadDir/xxx.png";
            var file = fs.createWriteStream(randomFileName);
            var request = http.get(downloadUrl, function(response) {
                response.pipe(file);
            });
            console.log("Image saved to dir");
        });
    }
});
```

**Comment by alexandercerutti** [comment]
Else, you may create a single bot with a bridge-component that has both interfaces, maybe both webhooks but with different ports bound for Telegram and Discord or one polling and one webhook or whatever. Your application will get triggered with Telegram image, get it with the way showed by @sidelux or as base64 raw (if possible) and send it on Discord. Obliviously you have to check the documentation.

**Comment by rraallvv** [comment]
@sidelux I'm getting this error over and over using your snippet:

```
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: file id not specified
    at request.then.resp (/Users/developer/Desktop/Nimiq/TeleTweet/node_modules/node-telegram-bot-api/src/telegram.js:280:15)
    at tryCatcher (/Users/developer/Desktop/Nimiq/TeleTweet/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/developer/Desktop/Nimiq/TeleTweet/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/developer/Desktop/Nimiq/TeleTweet/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/developer/Desktop/Nimiq/TeleTweet/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/developer/Desktop/Nimiq/TeleTweet/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/developer/Desktop/Nimiq/TeleTweet/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/developer/Desktop/Nimiq/TeleTweet/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/developer/Desktop/Nimiq/TeleTweet/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/developer/Desktop/Nimiq/TeleTweet/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
```

**Comment by sidelux** [comment]
probably file_id is not specified, try to debug with
`console.log(message.photo[0]);`
before bot.getFile line

**Comment by rraallvv** [comment]
@sidelux thanks for the quick reply, I've already done that, that's how I was able to do the request as described in the SO answer. Is there some cache that need to be cleared, or a cooldown timer for using the API?

**Comment by rraallvv** [comment]
@sidelux This is how I was able to get an image from Telegram and post it to Twitter

```
const message = msg.caption.match(telegramRegex)[1];
const fileId = msg.photo[msg.photo.length - 1].file_id;
request(`https://api.telegram.org/bot${settings.telegram.token}/getFile?file_id=${fileId}`, (error, response, body) => {
	const filePath = JSON.parse(body).result.file_path;
	console.log(`https://api.telegram.org/file/bot${settings.telegram.token}/${filePath}`);
	request({
		url: `https://api.telegram.org/file/bot${settings.telegram.token}/${filePath}`,
		encoding: 'binary',
		headers: {
			"Connection": "keep-alive"
		}
	}, (error, response, body) => {
		const base64 = Buffer.from(body, 'binary').toString('base64');
		twitterBot.post('media/upload', { media: base64 }, (error, data, response) => {
			const mediaId = data.media_id_string;
			twitterBot.post('media/metadata/create', { media_id: mediaId }, (error, data, response) => {
				const params = { status: message, media_ids: [mediaId] };
				twitterBot.post('statuses/update', params, (error, data, response) => {
				})
			});
		});	
	});
});
```

I have no idea why it doesn't work with `getFileLink` though.

**Comment by sidelux** [comment]
> @sidelux thanks for the quick reply, I've already done that, that's how I was able to do the request as described in the SO answer. Is there some cache that need to be cleared, or a cooldown timer for using the API?

In some functions Telegram use cache, but you can't clear it...

**Comment by rraallvv** [comment]
@sidelux Thanks.
