### ISSUE TITLE
send BytesIO instead of file

### ISSUE THREAD

**Issue by erikfa** [yagop/node-telegram-bot-api#60]
I have a file that is stored in a \<type '_io.BytesIO'> and try to send it with either sendDocument or sendPicture, but there is an error in 
https://github.com/nickoala/telepot/blob/master/telepot/__init__.py#L198
The function only check if the type is a file and not other byteobjects.
```python
image = io.BytesIO(get_image()) #pipes an image
print type(image)
#<type '_io.BytesIO'>
bot.sendDocument(user, image) # This doesn't work. Get the error below.

"""Output:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 379, in handle
    callback(update['message'])
  File "./telegram_daemon.py", line 133, in handle
    bot.sendDocument(user, image)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 303, in sendDocument
    return self._sendFile(document, 'document', {'chat_id': chat_id, 'reply_to_message_id': reply_to_message_id, 'reply_markup': reply_markup})
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 294, in _sendFile
    return self._parse(r)
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 244, in _parse
    raise BadHTTPResponse(response.status_code, response.text)
BadHTTPResponse: (414, u'<html>\r\n<head><title>414 Request-URI Too Large</title></head>\r\n<body bgcolor="white">\r\n<center><h1>414 Request-URI Too Large</h1></center>\r\n<hr><center>nginx/1.9.1</center>\r\n</body>\r\n</html>\r\n')
"""
```

**Comment by yagop** [comment]
Python?
