### ISSUE TITLE
Problems with a welcome message and the rest of the commands

### ISSUE THREAD

**Issue by DestroyerIV** [yagop/node-telegram-bot-api#600]
Hi, I've been experiencing an error for a while. Until recently everything worked correctly, but out of nowhere it shows me the following error:

Unable to read property 'username' from undefined
It happens with all the properties:
msg.new_chat_member.first_name
msg.new_chat_member.id

I understand that if it were not defined, it would show this error, but if it is defined. I show you the code

```
bot.on('message',function(msg, match){
    console.log(msg);

    var chatId = msg.chat.id;
    var newUserName = msg.new_chat_member.username;
    var newUserId = msg.new_chat_member.id;
    var firstName = msg.new_chat_member.first_name;
    var messageId = msg.message_id;

    if(msg.new_chat_members != undefined){
        
        bot.deleteMessage(msg.chat.id, messageId);
    	bot.sendMessage(msg.chat.id, "¡Hola " + firstName + ", bienvenid@ al grupo " + msg.chat.title)
            } 
        });
```
Given this error, it does not let me execute any other function / command

Thanks in advance

**Comment by sidelux** [comment]
You must assign that variables ONLY when msg.new_chat_members != undefined, so:

```
//.....
var chatId = msg.chat.id;
var messageId = msg.message_id;

if (msg.new_chat_members != undefined){
    var newUserName = msg.new_chat_member.username;
    var newUserId = msg.new_chat_member.id;
    var firstName = msg.new_chat_member.first_name;

    //....
}
```

**Comment by kamikazechaser** [comment]
@NatalieChin80  Post your code, so that we can see it.

**Comment by NatalieChin80** [comment]
I currently have the following. As above, I was trying to make use of the `new_chat_members` event. The new chat message works only when the `bot.on('message')` part is commented out. Can we not have multiple `bot.on`? Or am I missing something? 

```
bot.on("new_chat_members", function (msg) {
    console.log(msg.new_chat_members);
    console.log(msg.new_chat_members[0].first_name);
    bot.sendMessage(msg.chat.id, "Hello " + msg.new_chat_members[0].first_name);
})
bot.on('message', (msg) => {
//other code
});
```

**Comment by sidelux** [comment]
Event `new_chat_members` not longer exists.
You should use:
```
bot.on('message', (msg) => {
    if (msg.new_chat_members != undefined)
        console.log(message.new_chat_member);
});
```

**Comment by NatalieChin80** [comment]
Does that work for you? Even if I change my code to this, I'm getting polling error. I do not have multiple instances of the bot running and commented all the other bot code.  

```
const TelegramBot = require('node-telegram-bot-api');
const token = xxxxxxxx;
const bot = new TelegramBot(token, {
    polling: true
});

bot.on('message', (msg) => {
    if (msg.new_chat_members != undefined) {
        console.log(message.new_chat_member);
    }
});
```

**Comment by sidelux** [comment]
It's a copy paste from my code.
So, change bot.on line with `bot.on('msg', function (message) {`.
My fault.

**Comment by NatalieChin80** [comment]
Ahhhh. I got it. Thanks @sidelux!

**Comment by Magush26** [comment]
Hey guys, I'm trying to delete the previous message of my bot to reduce flood but I get:ETELEGRAM: 400 Bad Request: message can't be deleted. The code:
const TelegramBot = require('node-telegram-bot-api');
const TeleBot = require('telebot');

const token = token;
const bot = new TelegramBot(token, {polling: true});

  bot.on("new_chat_members", function(msg) {

    bot.deleteMessage(msg.chat.id, msg.message_id)

    setTimeout(function(){
    var chatId = msg.chat.id;
    var messageId = msg.message_id;
    }, 500);

    if (msg.new_chat_members != undefined){
      if (msg.new_chat_member.id != undefined){
      var newUserName = msg.new_chat_member.username;
      } else {
      var newUserName = msg.new_chat_member.first_name;
      }
    }
    console.log(msg);

    bot.sendMessage(msg.chat.id, 'Hi @' + newUserName + ', thanks for joining our community!

**Comment by sidelux** [comment]
@Magush26 You should do something like this:
```
bot.sendMessage(msg.chat.id, 'Hi @' + newUserName + ', thanks for joining our community!").then(function (data) {
    setTimeout(function(){
        bot.deleteMessage(data.chat.id, data.message_id);
    }, 500);
});
```

**Comment by Magush26** [comment]
@sidelux thank you for the answer, can't seem to get my head around it. What I basically want is that if 10 people join my chat, the bot will only show one message referencing the last person. So it needs to keep deleted its previous messages. The way I have it now, it just deletes the previous message in the chat, not from the bot. Sorry, I'm new to this, appreciate all the help

**Comment by sidelux** [comment]
@Magush26 It's not so easy to understand your way, anyway, open new issue with some example and your code (well formatted) so other people can help you and not mess up this issue

**Comment by NexKo** [comment]
hi guys. i have a problem with new_chat_members. i want kick the new member after 5 minutes from to join .

```javascript
bot.on('message', function (msg) {
  if (msg.new_chat_members != undefined)
      const chatid = msg.chat.id
      const userid = msg.new_chat_members
      setTimeout(function(){
          bot.kickChatMember(chatid, userid)
      }, 300)
})
```
bot is dead with this code. if i delete this code, bot answer at the commands

**Comment by sidelux** [comment]
Replace the first line with:
`bot.on("message", function(msg) {`

**Comment by sidelux** [comment]
@NexKo try to debug with console.log to know where it stops working.

**Comment by NexKo** [comment]
@sidelux 
const chatid = msg.chat.id
        ^^^^^

SyntaxError: Unexpected token const
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)

**Comment by sidelux** [comment]
Try to use let or var to declare

**Comment by alexandercerutti** [comment]
Curly braces are missing on the IF.
With that snippet, `chatid` is created only in that IF.

So, probably, it dies because it cannot find `chatid`.

**Comment by rezamasrori** [comment]
how to close Chat section in node js by node-telegram-bot-api

**Comment by bluetyphoon77** [comment]
> Event `new_chat_members` not longer exists. You should use:
> 
> ```
> bot.on('message', (msg) => {
>     if (msg.new_chat_members != undefined)
>         console.log(message.new_chat_member);
> });
> ```

Hi,
Is it still today the only way to grab new users data when they join a group ?
thanks a lot
