### ISSUE TITLE
telegram bot / how can i use call back data // node.js

### ISSUE THREAD

**Issue by Chorogon** [yagop/node-telegram-bot-api#637]
```
const TelegramBot = require('node-telegram-bot-api');
 
// replace the value below with the Telegram token you receive from @BotFather
const token = '636841968:AAEVUaeBqww2vTF1su1yJGmS5QMqnZBKtp0';
 
// Create a bot that uses 'polling' to fetch new updates
const bot = new TelegramBot(token, {polling: true});
 
// Matches "/echo [whatever]"


// 'msg' is the received Message from Telegram
// 'match' is the result of executing the regexp above on the text content
// of the message
//const resp = match[]; // the captured "whatever"
// send back the matched "whatever" to the chat
//bot.sendMessage(chatId, resp);
//bot.sendPhoto(chatId, resp);
bot.onText(/\도움/, (msg) => {
  var opts ={
       reply_markup: {
           inline_keyboard: [
               [{text:"지옥문", url: "http://masca.dothome.co.kr/"}],
               [{text:"엔더월드 가는법", callback_data: "2"}],
               [{text:"TNT 만드는법", callback_data: "3"}],
               [{text:"케이크 만드는법", callback_data: "4"}],
               [{text:"황금사과 만드는법", callback_data: "5"}],
               [{text:"양털 채집", callback_data: "6"}],
               [{text:"책장 만드는법", callback_data: "7"}],
               [{text:"인첸트 하는법", callback_data: "8"}],
               [{text:"엔더드래곤 잡는법", callback_data: "9"}],
               [{text:"위더 소환법", callback_data: "10"}],
               [{text:"음반 얻는법", callback_data: "11"}],
               [{text:"농사 시작하는법", callback_data: "11"}],
               [{text:"무한 물 만드는법", callback_data: "12"}],
               [{text:"주의사항", callback_data: "13"}]
           ]
       } 
       
   };
    bot.sendMessage(msg.from.id,"이중 하나를 골라주세요",opts);
});

bot.on("callback_query", function(data){
    const chatId = msg.id;
    console.log(data);
    bot.answerCallbackQuery(chatId,'hello'); 
    
});
```

It doesn't work when I press the button.
How can I use callback data?
and how can i use  [ url ] Parameters?

**Comment by Chorogon** [comment]
Thank you for your answer. 
yes. I mean it does not call the 'callback_query' event when I press the button
and I found the new problem in the console
`
0|index    | error: [polling_error] {}

`
I have no idea to fix this problem 
can you help me to solve these problems plz?

**Comment by DtCarrot** [comment]
Can you add the following event listener and give the output? I tried running the above code on my end and it seemed to work fine. Any other errors you can see?

`bot.on('polling_error', error => console.log(error))`

**Comment by Chorogon** [comment]
```
0|index    | error: [polling_error] {}
0|index    | error: [polling_error] {}
0|index    | error: [polling_error] {}
0|index    | error: [polling_error] {}
0|index    | error: [polling_error] {}
0|index    | error: [polling_error] {}
0|index    | error: [polling_error] {}
0|index    | error: [polling_error] {}
0|index    | error: [polling_error] {}
0|index    | Wed, 05 Sep 2018 14:40:43 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
0|index    | In the future, you will have to enable it yourself.
0|index    | See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:652:30
0|index    | Fri, 07 Sep 2018 09:46:55 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
0|index    | In the future, you will have to enable it yourself.
0|index    | See https://github.com/yagop/node-telegram-bot-api/issues/319. at module.js:652:30
```

I added your code to my index.js, but it still generates the error.

**Comment by Chorogon** [comment]
thank you, lastly, how to use chatId outside of this cord?
```
bot.onText(/\도움/, (msg) => {
 var opts ={
       reply_markup: {
           inline_keyboard: [
               [{text:"지옥문", callback_data: "1"}],
               [{text:"엔더월드 가는법", callback_data: "2"}],
               [{text:"TNT 만드는법", callback_data: "3"}],
               [{text:"케이크 만드는법", callback_data: "4"}],
               [{text:"황금사과 만드는법", callback_data: "5"}],
               [{text:"양털 채집", callback_data: "6"}],
               [{text:"책장 만드는법", callback_data: "7"}],
               [{text:"인첸트 하는법", callback_data: "8"}],
               [{text:"엔더드래곤 잡는법", callback_data: "9"}],
               [{text:"위더 소환법", callback_data: "10"}],
               [{text:"음반 얻는법", callback_data: "11"}],
               [{text:"농사 시작하는법", callback_data: "11"}],
               [{text:"무한 물 만드는법", callback_data: "12"}],
               [{text:"동대부고", url: "http://www.ddbk.hs.kr/index.do"}],
               
           ]
       } 
       
   };
    bot.sendMessage(msg.from.id,"이중 하나를 골라주세요",opts);
bot.on("callback_query", function(data){
    const chatId = msg.id;
    console.log(data.data);
});
});
```
I want to send a message following callback_data such as "9",

**Comment by DtCarrot** [comment]
Within your callback function, you can simply retrieve the callback_data using data.data. You can have an if condition to send a message depending on the callback data.

`bot.on("callback_query", function(data){
    const chatId = msg.id;
    const data = data.data
    if(data == "9") {
      // Message you want to send for callback_data "9"
    }
});`

**Comment by Chorogon** [comment]
Thanks
