### ISSUE TITLE
EFATAL after long idle time

### ISSUE THREAD

**Issue by Cm-8** [yagop/node-telegram-bot-api#641]
> Question

I'm developing a bot on my local machine, with nodejs 8.11.4.
I'm using only node-telegram-bot-api library.

my BOT work well done, but if in the night i leave it on, the morning after, when i come back to office my BOT is blocked and show error: EFATAL

is it because i'm using it without SSL certificate?
how do I trace the error?
I entered the code (take here [usage.md](https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md)):
```
bot.on ('polling_error', (error) => {
   console.log (error.code); // => 'EFATAL'
});
```
but I see only the EFATAL message, no description:

![screenshot_118](https://user-images.githubusercontent.com/21364091/45419308-40467680-b687-11e8-987a-ed97fc222819.png)

Thank you for support

**Comment by sidelux** [comment]
Use error.message or error.stack to debug.

**Comment by Cm-8** [comment]
Thanks, now i try with:

```
// Listen on the 'polling_error' event
bot.on('polling_error', (error) => {
	var time = new Date();
	console.log("TIME:", time);
	console.log("CODE:", error.code);  // => 'EFATAL'
	console.log("MSG:", error.message);
	console.log("STACK:", error.stack);
});
```

**Comment by sidelux** [comment]
Is that useful but for example Unhandled Exception emitted by node is not captured by polling_error.

**Comment by Cm-8** [comment]
You suggest to add something like this?

```
bot.on('uncaughtException', (error) => {
	var time = new Date();
	console.log("TIME:", time);
	console.log("POLL_CODE:",error.code);
	console.log("MSG:",error.message);
	console.log("STACK:",error.stack);	
});
```

**Comment by sidelux** [comment]
Yes ;)

**Comment by Cm-8** [comment]
Top! e Grazie ;)

**Comment by Cm-8** [comment]
After @sidelux advice, I added more code for debugging, now I get many times the error:
**ETELEGRAM: 502 Bad Gateway**

I see that someone had a similar problem in 2016 here: 
https://github.com/yagop/node-telegram-bot-api/issues/89

How to solve or automatically restart the bot?

```
TIME:  2018-09-18T01:13:05.811Z
POLL_CODE:  ETELEGRAM
MSG:  ETELEGRAM: 502 Bad Gateway
STACK:  Error: ETELEGRAM: 502 Bad Gateway
    at request.then.resp (D:\app\TelegramBot\node_modules\node-telegram-bot-api\src\telegram.js:280:15)
    at tryCatcher (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```


```
TIME:  2018-09-18T01:13:06.186Z
POLL_CODE:  ETELEGRAM
MSG:  ETELEGRAM: 502 Bad Gateway
STACK:  Error: ETELEGRAM: 502 Bad Gateway
    at request.then.resp (D:\app\TelegramBot\node_modules\node-telegram-bot-api\src\telegram.js:280:15)
    at tryCatcher (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

```
TIME:  2018-09-18T01:13:06.874Z
POLL_CODE:  ETELEGRAM
MSG:  ETELEGRAM: 502 Bad Gateway
STACK:  Error: ETELEGRAM: 502 Bad Gateway
    at request.then.resp (D:\app\TelegramBot\node_modules\node-telegram-bot-api\src\telegram.js:280:15)
    at tryCatcher (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (D:\app\TelegramBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by sidelux** [comment]
I think you can only restart node in that case.
Try to follow [this steps](https://stackoverflow.com/questions/23766259/restart-node-js-server-programmatically) but i think you should use node server manager like pm2 o forever.

**Comment by patrickbard** [comment]
> my BOT work well done, but if in the night i leave it on, the morning after, when i come back to office my BOT is blocked and show error: EFATAL

I'm in the same situation here

**Comment by sidelux** [comment]
@patrickbard with error 502?
If it happens once only it's a telegram problem, alternatively read [this](#issuecomment-422336197) comment.

**Comment by Cm-8** [comment]
@patrickbard what kind of error?

For promise error, please insert: 

`process.env.NTBA_FIX_319 = 1;   // fix cancellation of promises https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:652:30`

at first line of your BOT
