### ISSUE TITLE
Error on User Send Location

### ISSUE THREAD

**Issue by Cm-8** [yagop/node-telegram-bot-api#650]
> Question

I receive this error every time a user sent their position to my bot:

```
MSG:  Cannot read property 'toString' of undefined
STACK:  TypeError: Cannot read property 'toString' of undefined
    at TelegramBot.bot.on (D:\app\TBot\app.js:83:17)
    at TelegramBot.emit (D:\app\TBot\node_modules\node-telegram-bot-api\node_modules\eventemitter3\index.js:182:35)
    at TelegramBot.processUpdate (D:\app\TBot\node_modules\node-telegram-bot-api\src\telegram.js:594:12)
    at updates.forEach.update (D:\app\TBot\node_modules\node-telegram-bot-api\src\telegramPolling.js:110:22)
    at Array.forEach (<anonymous>)
    at _lastRequest._getUpdates.then.updates (D:\app\TBot\node_modules\node-telegram-bot-api\src\telegramPolling.js:106:17)
    at tryCatcher (D:\app\TBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\app\TBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\app\TBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\app\TBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\app\TBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\app\TBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\app\TBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\app\TBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (D:\app\TBot\node_modules\node-telegram-bot-api\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by sidelux** [comment]
Can you post your code part?

**Comment by Cm-8** [comment]
This is my code:
I have three BOTs and also the other two when the client sends the position show the previous error.

```
process.env.NTBA_FIX_319 = 1;   // fix cancellation of promises https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:652:30

const TelegramBot = require('node-telegram-bot-api');

// replace the value below with the Telegram token you receive from @BotFather
const token = 'XXX-XXX';

// Create a bot that uses 'polling' to fetch new updates
const bot = new TelegramBot(token, {polling: true});



// Start Message
bot.onText(/\/start/, (msg) => {

    bot.sendMessage(msg.chat.id, "Welcome You "+ msg.from.first_name +", \nI'm <b>bot</b> and I'm here to help you to find ...",{parse_mode : "HTML"}
	);
	
});

// Help Message
bot.onText(/\/help/, (msg) => {

    bot.sendMessage(msg.chat.id, "I can share with you the contact of the nearest ...",{parse_mode : "HTML"}
	);
	
});

// Site Message -> Go to our website
bot.onText(/\/site/, (msg) => {

    bot.sendMessage(msg.chat.id, "Do you need a ...",{parse_mode : "HTML"}
	);
	
});

// List Message -> List of available city
bot.onText(/\/list/, (msg) => {

    bot.sendMessage(msg.chat.id, "Do you need ...",{parse_mode : "HTML"}
	);
	
});


// Listen for any kind of message. There are different kinds of  messages.
bot.on('message', (msg, match) => {
  
  var time = new Date();
  
  const chatId = msg.chat.id;  //ID of who write to us
  const U_Name = msg.from.username;
  const F_Name = msg.from.first_name;
  const lang = msg.from.language_code;
  console.log("TIME:", time);
  console.log("USER:", "ID:"+chatId ,"USER_NAME:"+U_Name ,"FIRST_NAME:"+F_Name );
  //console.log("MSG COMPLETE:", msg);    // See all content of the message
  
  bot.sendMessage(XXXXXXXX, "<b>**Someone use me:**</b>\nID: " + chatId +"\nUSER_NAME: " + U_Name +"\nFIRST_NAME: "+ F_Name + "\nMSG: "+ msg.text + "\nLang: "+lang ,{parse_mode : "HTML"});    // Advice owner
  
  
  if (msg.hasOwnProperty('text')) {
	const txt = msg.text;
	console.log("TESTO:", txt);
  } 
  
  if (msg.hasOwnProperty('location')) {
	const loc = msg.location;
	bot.sendMessage(msg.chat.id, "Dear "+ msg.from.first_name +", \nSorry, at the moment I can't send you ... write me the name of the city where you are." +
	"\n\nPlease type: \n<b>The name of the city where you are</b>, or \n/help -  To have support\n/list  -  To know the list of available city\n/site  -  To visit our website",{parse_mode : "HTML"});
	console.log("LOCATION:", loc);
  }

  if (msg.hasOwnProperty('contact')) {
	
  } else {
	  
	  // Se l'utente indica la città, gestisci.
	  
	  const padova = "padova";
	  if (msg.text.toString().toLowerCase().includes(padova)) {
		  bot.sendMessage(msg.chat.id, "If you need ...",{parse_mode : "HTML"});
	  }
	  
	  const roma = "roma";
	  if (msg.text.toString().toLowerCase().includes(roma)) {
		  bot.sendMessage(msg.chat.id, "If you need ...",{parse_mode : "HTML"});
	  }
	  
	  const milano = "milano";
	  if (msg.text.toString().toLowerCase().includes(milano)) {
		  bot.sendMessage(msg.chat.id, "If you need ...",{parse_mode : "HTML"});
	  }
	  
	  // Gestisci Saluto  
	  const bye = "bye";
	  if (msg.text.toString().toLowerCase().includes(bye)) {
		  bot.sendMessage(msg.chat.id, "Glad to have been useful,..., Bye!");
	  }  
	}  
  
});




// Listen on the 'polling_error' event
bot.on('polling_error', (error) => {
	var time = new Date();
	console.log("TIME: ",time);
	console.log("POLL_CODE: ",error.code);  // => 'EFATAL'
	console.log("MSG: ",error.message);
	console.log("STACK: ",error.stack);
});

bot.on('uncaughtException', (error) => {
	var time = new Date();
	console.log("TIME: ",time);
	console.log("NODE_CODE: ",error.code);  // => 'NODE JS'
	console.log("MSG: ",error.message);
	console.log("STACK: ",error.stack);	
});

// Listen on the 'webhook_error' event
bot.on('webhook_error', (error) => {
	var time = new Date();
	console.log("TIME: ",time);
	console.log("WEB_CODE: ",error.code);  // => 'EPARSE'
	console.log("MSG: ",error.message);
	console.log("STACK: ",error.stack);
});


console.log('\x1b[33m%s\x1b[0m', " *** Bot v1.0 has started. *** ");  //yellow
```

**Comment by sidelux** [comment]
I think you should add here:
```
const padova = "padova";
if (msg.text.toString().toLowerCase().includes(padova)) {
    bot.sendMessage(msg.chat.id, "If you need ...",{parse_mode : "HTML"});
}
```
an extra if with msg.text verification for example:
```
const padova = "padova";
if ((msg.hasOwnProperty('text')) && (msg.text.toString().toLowerCase().includes(padova))) {
    bot.sendMessage(msg.chat.id, "If you need ...",{parse_mode : "HTML"});
}
```

**Comment by Cm-8** [comment]
@sidelux thanks for the instructions, **it works**!
I did better, I moved Padova and all the similar in the previous if:

```
  if (msg.hasOwnProperty('text')) {
	const txt = msg.text;
	console.log("TESTO:", txt);

        *** all here  ***

  } 
```
