### ISSUE TITLE
How to remove  messages from Telegram

### ISSUE THREAD

**Issue by sinahedayati** [yagop/node-telegram-bot-api#653]
I have a supergroup in Telegram and a Bot, which is administrator of a group. Bot is based on your code. When a new user join or left group, service message (with grey background) is appear in chat, for example

Username join to a chat
Username is join to a chat by invite link
Username is left the chat

Is it possible to catch and delete such service messages from chat with Bot API?

Thank you in advance!

**Comment by jejopl** [comment]
`    if(msg.new_chat_member !== undefined || msg.left_chat_member !== undefined ){
        bot.deleteMessage(msg.chat.id, msg.message_id);
    }`

Note: I'm usually adding a delay before deleting, before in some rare cases, message was deleted but was still visible to some users.

`    if(msg.new_chat_member !== undefined){
        setTimeout(() => {
            bot.deleteMessage(msg.chat.id, msg.message_id);
        }, 1500);
    }`

**Comment by sinahedayati** [comment]
> I'm usually adding a delay before deleting because in some rare cases, the message was deleted but it was still visible to some users.

tanks a lot
 but i want delete message telegram invited
user addedd username 
or 
user remove username
tanks

**Comment by jejopl** [comment]
I know, that's why there's an `if` in my code

`if(msg.new_chat_member !== undefined) ` it's true only when new user will join/will be invited
`if(msg.left_chat_member !== undefined)` it's true only when new user will leave/will be banned

And then (only if it's true) you have `bot.deleteMessage(msg.chat.id, msg.message_id);`

So bot will remove this message.

**Comment by sinahedayati** [comment]
tanks 

mycode is : 

bot.on('message', (msg) => {

    if(msg.new_chat_member !== undefined || msg.left_chat_member !== undefined){
        setTimeout(() => { bot.deleteMessage(msg.chat.id, msg.message_id); }, 1500);
    } 


});



 my error is:
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: message can't be deleted
    at request.then.resp (C:\xampp\htdocs\telegram-bot\node_modules\node-telegram-bot-api\src\telegram.js:280:15)
    at tryCatcher (C:\xampp\htdocs\telegram-bot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\xampp\htdocs\telegram-bot\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\xampp\htdocs\telegram-bot\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\xampp\htdocs\telegram-bot\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\xampp\htdocs\telegram-bot\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (C:\xampp\htdocs\telegram-bot\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\xampp\htdocs\telegram-bot\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\xampp\htdocs\telegram-bot\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\xampp\htdocs\telegram-bot\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

**Comment by jejopl** [comment]
Check if your bot has the admin rights

**Comment by sinahedayati** [comment]
Thank you so much

**Comment by kamikazechaser** [comment]
Question seems to be resolved, closing it for now.

**Comment by rezamasrori** [comment]
how to close Chat section in node js by node-telegram-bot-api ????

**Comment by a5okol** [comment]
```
bot.on("new_chat_members", (msg) =>
  bot.deleteMessage(msg.chat.id, msg.message_id)
);
bot.on("left_chat_member", (msg) => {
  bot.deleteMessage(msg.chat.id, msg.message_id);
});
```
