### ISSUE TITLE
Fails when trying to retrieve "large" files.

### ISSUE THREAD

**Issue by LuisDiazUgena** [yagop/node-telegram-bot-api#697]
> Bug Report

I have read:

* [Usage information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/usage.md)
* [Help information](https://github.com/yagop/node-telegram-bot-api/tree/master/doc/help.md)

I am using the latest version of the library.

### Expected Behavior

Download a file and store it to pass it as a parameter to another program.

### Actual Behavior

Console shows a error: _File is too big_.

### Steps to reproduce the Behavior

Create a new bot with this code:

```
const TelegramBot = require('node-telegram-bot-api');
const hhtp = require('http')
const fs = require('fs')

const token = 'XXXXXXXXXXX';
const bot = new TelegramBot(token, {polling: true});

bot.onText(/\/start/, (msg) => {
    bot.sendMessage(msg.chat.id, "Hello "+msg.from.first_name+"\n\nWelcome");
});

bot.on('message', (msg) => {
    console.log(msg)
    const chatId = msg.chat.id;

    if(msg.document != undefined){
        bot.sendMessage(chatId,'Received your document '+msg.document.file_name);
        if(msg.document.file_name.match('.BFL')){
            bot.sendMessage(chatId,'It\'s a log!')
            console.log("\n\n\n\n\n\nIt\'s a log!")

            bot.getFile(msg.document.file_id).then(function (fileData) {
                console.log("fileData")
                // console.log(fileData)
                // var downloadUrl = fileData.file_path;
                // var randomFileName = "downloadDir/xxx.png";
                // var file = fs.createWriteStream(randomFileName);
                // var request = http.get(downloadUrl, function(response) {
                //     response.pipe(file);
                // });
                // console.log("File saved to dir");
            })
        }else{
            bot.sendMessage(chatId,'Please, send BFL or BFF files only')
        }
    }
});

bot.on('polling_error', (error) => {
  console.log("Error: "+error.code);  // => 'EFATAL'
});
ales

```

Start the bot and send a "large" file. I'm using this:
[LOG00032.zip](https://github.com/yagop/node-telegram-bot-api/files/2813139/LOG00032.zip)

and the error that it's printed on the console is:

```
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: file is too big
    at request.then.resp (FakePath\node_modules\node-telegram-bot-api\src\telegram.js:280:15)
    at tryCatcher (FakePath\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (FakePath\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (FakePath\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (FakePath\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (FakePath\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (FakePath\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (FakePath\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (FakePath\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (FakePath\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)

```

**Comment by LuisDiazUgena** [comment]
Just found that it's a Telegram Api limitation, bots can download up to 20 mb.
