### ISSUE TITLE
GCP does not allow the bot to work

### ISSUE THREAD

**Issue by SimaxSaab** [yagop/node-telegram-bot-api#812]
I uploaded a bot on Google Cloud Platform using Firebase and got an error:

>error: [polling_error] {"code":"EFATAL","message":"EFATAL: Error: getaddrinfo EAI_AGAIN api.telegram.org:443"}

Then i inserted the following code:

```javascript
bot.on("polling_error", (err) => console.log(err));
```

And got such an error:

>RequestError: Error: getaddrinfo EAI_AGAIN api.telegram.org:443
    at new RequestError (/srv/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/srv/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/srv/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/srv/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/srv/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9) code: 'EFATAL'

Please help to solve this, thank you!

**Comment by oscrx** [comment]
Do other dns queries work?

**Comment by danielperez9430** [comment]
In the end your problem is related to the "GCP Firewalls", because you have the port 443 (https) close
