### ISSUE TITLE
testing bot api is not working  

### ISSUE THREAD

**Issue by j-shn** [yagop/node-telegram-bot-api#953]
> Bug Report

### Expected Behavior

- mock api calls with for testing (jest)

### Actual Behavior

the api seems to be breaking the code. The library was updated so this doesnt seem to be the issue. 

### Steps to reproduce the Behavior

I emulated the issue here. I am learning to write tests so there could be some logic error, but I do not think it is the main reason for the issue even if there is one. I have persistently been getting `TypeError: Cannot read properties of undefined (reading 'split')`

https://codesandbox.io/s/naughty-pond-zzob06?file=/src/index.ts:58-61

**Comment by ssuvorov** [comment]
Yes, so on a sandbox while reproducing we have the next error:
```js
Cannot read properties of undefined (reading 'split')

TypeError: Cannot read properties of undefined (reading 'split')
    at Window.$csb$eval (https://x1ot1k.csb.app/node_modules/node-telegram-bot-api/index.js:6:53)
```

And I found people tried to use a 'nock' lib. So the next code also catches another error
```js
const nock = require('nock');
const TelegramBot = require('node-telegram-bot-api');
```

```js
    TypeError: Cannot read property 'MAX_SAFE_INTEGER' of undefined

      at Object.<anonymous> (node_modules/es-abstract/helpers/maxSafeInteger.js:8:26)
      at Object.<anonymous> (node_modules/es-abstract/2019/ToLength.js:3:24)
```

**Comment by danielperez9430** [comment]
> > Bug Report
> 
> ### Expected Behavior
> * mock api calls with for testing (jest)
> 
> ### Actual Behavior
> the api seems to be breaking the code. The library was updated so this doesnt seem to be the issue.
> 
> ### Steps to reproduce the Behavior
> The issue is emulated below:
> 
> https://codesandbox.io/s/nostalgic-chaum-x1ot1k?file=/package.json

Hi, your problem is that your "codesanbox" is for web context and this library is not for browsers.
